### PR TITLE
add setup.py

### PR DESCRIPTION
**Pull request by mreineck**
This file should allow installing the Python package via
`python setup.py install` and `pip install`.

The toplevel package is `cobraOps` and not `ics`, because otherwise it might become difficult to install several `ics` packages at the same time.

### CODE REVIEW

**Comment by mreineck** [comment]
I adjusted the import statements as well.
Unfortunately, my editor removed trailing white space, so that diff looks terrifying...

**Comment by jagracar** [comment]
Thank you for the changes, Martin. Can you move collisionStatistics.py to the new demos directory? I will merge after that, unless you are planning more changes

**Comment by mreineck** [comment]
Done!
Couldn't really test collisionStatistics.py, because it crashed on me with:
```
  File "collisionStatistics.py", line 66, in <module>
    simulator.run()
  File "/home/martin/.local/lib/python3.5/site-packages/cobraOps-0.0.0-py3.5.egg/cobraOps/CollisionSimulator.py", line 90, in run
  File "/home/martin/.local/lib/python3.5/site-packages/cobraOps-0.0.0-py3.5.egg/cobraOps/CollisionSimulator.py", line 199, in defineMovementDirections
Exception: Some cobras cannot reach their assigned targets because the trajectorySteps parameter value is too low. Please set it to a higher value.


```

**Comment by jagracar** [comment]
Thanks, yes probably the default value in the CollisionSimulator constructor is two low and I should increase it a bit. 

I will merge the branch. Thanks!

**Pull request merged**
